version: "3.8"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    env_file: .env
    expose:
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: unless-stopped
    networks:
      - webapp-network

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    env_file: .env
    expose:
      - 9000
    volumes:
      - wp-volume:/var/www/
    restart: unless-stopped
    networks:
      - webapp-network

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    env_file: .env
    ports:
      - 443:443
    volumes:
      - wp-volume:/var/www/
    restart: unless-stopped
    networks:
      - webapp-network

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/olahmami/data/mariadb
      o: bind
  wp-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/olahmami/data/wordpress
      o: bind

networks:
  webapp-network:
    driver: bridge
